Task_1_2_2
Sibseven/OOP pull request #10
Opened 2024-10-29 06:58 UTC by Sibseven

2024-11-05 08:04 UTC, shadrina requested changes

2024-11-05 08:04 UTC, shadrina commented on Task_1_2_2/src/main/java/HashTable.java
> +    private List<ArrayList<Entry<K, V>>> table;
Хотя бы внешний сделать обычным массивом, потому что нет смысла в динамичности здесь

2024-11-05 08:04 UTC, shadrina commented on Task_1_2_2/src/main/java/HashTable.java
> +        addIfAbsent(key, value);
Будет некорректный `numOfChanges`

2024-11-05 08:04 UTC, shadrina commented on Task_1_2_2/src/main/java/HashTable.java
> +    private class HashTableIterator implements Iterator<Entry<K, V>> {
Точно ли соблюдается весь контракт?

2024-11-14 13:49 UTC, Sibseven commented
Вы просили убрать изменения из google checks в этой ветке. Помогите мне разобраться пожалуйста почему оно вообще отображается как изменение, если оно уже есть в мейн? я пробовал делать ребейз этой ветки на мейн, откатывать изменения к мейну для этого xml файла, оно не сработало, либо я не понимаю как работает ребейз. Разрешите смерджить таким образом?

2024-11-18 11:41 UTC, shadrina commented
Давай ты на паре подойдешь и мы вместе посмотрим.

2024-11-19 08:43 UTC, closed without merging