Task_1_1_1
Sibseven/OOP pull request #6
Opened 2024-09-05 16:39 UTC by Sibseven

2024-09-09 10:22 UTC, shadrina requested changes

2024-09-09 10:22 UTC, shadrina commented on Task_1_1_1/script.sh
> +javadoc src/main/java/heapsort.java
Как это работает? Не могу поверить, что утилиты не реагируют на регистр.

2024-09-09 10:22 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        assert (true == true);
`assertTrue`

2024-09-09 10:22 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +public class HeapsortTest {
Посмотри вкладку `Files changed`, есть варнинги от reviewdog.

2024-09-09 10:22 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +public class HeapsortTest {
На следующий раз: не нужно назначать ревью, если reviewdog рисует варнинги. Сначала их надо исправить.

2024-09-09 10:25 UTC, shadrina commented on .github/workflows/oop.yml
> +    branches: [ "main" ]
1) Эту ветку нужно обновить на текущее состояние main. Там уже есть это изменение.
2) В инструкции сразу стояла правильная ветка. Откуда ты взял `.github`?

2024-09-10 07:06 UTC, Sibseven commented on Task_1_1_1/script.sh
> +javadoc src/main/java/heapsort.java
забыл изменить название файла, исправлю

2024-09-10 07:11 UTC, Sibseven commented on .github/workflows/oop.yml
> +    branches: [ "main" ]
.github скачал с вашего репозитория zip архивом, потом добавил себе локально в папку

2024-09-10 07:11 UTC, Sibseven commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +public class HeapsortTest {
Извините, думал если "All checks have passed" загорается, значит все хорошо. Впредь не буду так делать

2024-09-10 07:12 UTC, Sibseven commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +        assert (true == true);
Хорошо, исправлю

2024-09-10 08:44 UTC, shadrina approved these changes

2024-09-10 09:10 UTC, merged