Task_1_1_2
Sibseven/OOP pull request #7
Opened 2024-09-13 05:58 UTC by Sibseven

2024-09-18 11:37 UTC, shadrina requested changes

2024-09-18 11:37 UTC, shadrina commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Card.java
> +    int value;
См. инкапсуляция, модификаторы доступа.
См. изменяемость структуры данных, модификатор final.

2024-09-18 11:37 UTC, shadrina commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Deck.java
> +        }
См. nullability аннотации, чтобы пользователь этого API не нарвался на NullPointerException

2024-09-18 11:37 UTC, shadrina commented on Task_1_1_2/src/test/java/nsu/lavrenenkov/HandTest.java
> +        assert hand.cards.size() == 2;
Желательно использовать assert'ы из выбранной библиотеки для тестирования.

2024-09-23 11:55 UTC, shadrina requested changes

2024-09-23 11:55 UTC, shadrina commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Card.java
> +package nsu.lavrenenkov;
По поводу пакетов озвучу проблему на паре

2024-09-23 11:55 UTC, shadrina commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Card.java
> +    private final String rang;
rank наверно

2024-09-23 11:55 UTC, shadrina commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Card.java
> +        if (i >= 1 && i <= 11) {
У вас еще не было лекции про исключения, но вообще в такой ситуации лучше делать `throw new IllegalArgumentException()`, если аргумент не соответствует ожидаемому. Либо, как вариант, в качестве параметра принимать не int, а свой enum, у которого фиксировано множество значений. Тогда клиент не сможет ошибиться.

2024-09-23 11:55 UTC, shadrina commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Deck.java
> +        int[] values = {2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 11};
Давай попробуем завести enum'ы под фиксированные множества значений. Сравнишь, как преобразится код.

2024-09-23 11:55 UTC, shadrina commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Deck.java
> +        }
Пусть нарвется, ты предупредил 😄

2024-09-23 17:00 UTC, Sibseven commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Deck.java
> +        }
я в итоге исправил проблему или нет? если нет, то что возвращать если не null?

2024-09-24 08:38 UTC, shadrina commented on Task_1_1_2/src/main/java/nsu/lavrenenkov/Deck.java
> +        }
Все норм, пусть будет так

2024-09-24 08:43 UTC, shadrina approved these changes
Использовать enum'ы

2024-09-24 09:11 UTC, merged