Task_1_1_3
Sibseven/OOP pull request #8
Opened 2024-09-22 10:22 UTC by Sibseven

2024-10-07 11:58 UTC, shadrina requested changes
Мало тестов, особенно сложных. В остальном ОК

2024-10-07 11:58 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/lavrenenkov/expression/Variable.java
> +        Matcher matcher = pattern.matcher(signification);
Расскажешь, как работает внутри Matcher

2024-10-07 11:58 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/lavrenenkov/expression/Variable.java
> +        Matcher matcher = pattern.matcher(signification);
Использовать тут регулярки - немного читерство

2024-10-08 09:06 UTC, shadrina reviewed
Что вообще такое hashCode?

2024-10-08 15:27 UTC, Sibseven commented
HashCode это метод класса Object, возвращаюший int, используется в хэш таблицах. Для объектов равных по equals он должен возращать одинаковые значения. Для объектов не равных по equals может возвращать одинаковые или разные. В рамках одного выполнения для одного объекта должен всегда возвращать разное(если информация об объекте, используемая в equals, не менялась). Для разных выполнений может не быть одинаковым для одного и того же объекта

2024-10-14 12:49 UTC, shadrina requested changes

2024-10-14 12:49 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/lavrenenkov/expression/Parser.java
> +        return new Number(0);
return switch expression please

2024-10-14 13:01 UTC, Sibseven commented on Task_1_1_3/src/main/java/ru/nsu/lavrenenkov/expression/Parser.java
> +        return new Number(0);
А я думал Вы зачли уже.... вы просили написать про hashCode, я написал выше в комментариях

2024-10-14 15:18 UTC, Sibseven commented on Task_1_1_3/src/main/java/ru/nsu/lavrenenkov/expression/Parser.java
> +        return new Number(0);
у меня локально собирается, а на гитхабе нет, это может быть связано с различием в версии gradle?

2024-10-15 07:18 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/lavrenenkov/expression/Parser.java
> +        return new Number(0);
Я зачла, но это не значит, что не нужно доводить код до наилучшего состояния.

2024-10-15 07:26 UTC, shadrina approved these changes

2024-10-22 07:45 UTC, merged